# Generated by Django 3.1.1 on 2020-09-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('포유류', '포유류'), ('조류', '조류'), ('양서파충류', '양서파충류'), ('어류', '어류'), ('곤충류', '곤충류'), ('무척추동물', '무척추동물')], max_length=20)),
                ('level', models.CharField(choices=[('1급', '1급'), ('2급', '2급'), ('3급', '3급')], max_length=10)),
                ('kor_name', models.CharField(max_length=30)),
                ('scientific_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
