# Generated by Django 3.1.1 on 2020-09-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20200905_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='group',
            field=models.CharField(choices=[('포유류', '포유류'), ('조류', '조류'), ('양서파충류', '양서파충류'), ('어류', '어류'), ('곤충류', '곤충류'), ('무척추동물', '무척추동물')], max_length=20),
        ),
        migrations.AlterField(
            model_name='friend',
            name='image',
            field=models.ImageField(default='static/images/default_image.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='friend',
            name='level',
            field=models.CharField(choices=[('1급', '1급'), ('2급', '2급'), ('3급', '3급')], max_length=10),
        ),
    ]
