# Generated by Django 3.1.1 on 2020-09-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_auto_20200905_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
