# Generated by Django 3.1.1 on 2020-09-05 19:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('columns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
