# Generated by Django 3.1.1 on 2020-09-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='images',
            field=models.ManyToManyField(null=True, to='reports.ReportImage'),
        ),
    ]
