# Generated by Django 3.1.1 on 2020-09-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='images',
            field=models.ManyToManyField(to='reports.ReportImage'),
        ),
    ]
