# Generated by Django 3.1.1 on 2020-09-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200905_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=models.ImageField(null=True, upload_to='report'),
        ),
    ]
