# Generated by Django 3.1.1 on 2020-09-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200906_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=models.ImageField(upload_to='report'),
        ),
    ]
